### ISSUE TITLE
How to run your program?

### ISSUE THREAD

**Issue by JafferWilson** [rustamli/rephrase#1]
Kindly update your readme file using the syntax for using your repository.
I hope to hear from you soon.

**Comment by rustamli** [comment]
hi @JafferWilson thanks for your interest, but unfortunately there's no way to run rephrase right now as it requires connection to text corpora I don't have access anymore. So unfortunately you won't be able to re-use this

**Comment by JafferWilson** [comment]
So this is a fake repository with no use for now. (sigh) My bad.... 
Well, Thank you for your reply.
